# Generated by Django 5.2 on 2026-02-16 22:14

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_display_name_useraccount_default_display_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventparticipant',
            name='unique_display_name_per_event',
        ),
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('display_name'), models.F('user_event'), name='unique_display_name_per_event'),
        ),
    ]
