# Generated by Django 5.2 on 2026-02-16 22:51

import api.models
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_display_name_useraccount_default_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlcode',
            name='created_at',
            field=api.models.DateTimeNoTZField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usersession',
            name='created_at',
            field=api.models.DateTimeNoTZField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
