# Generated by Django 5.2 on 2026-02-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_remove_eventparticipant_unique_display_name_per_event_and_more'),
        ('api', '0024_urlcode_created_at_usersession_created_at'),
    ]

    operations = [
    ]
