# Generated by Django 5.2 on 2026-03-27 19:16

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_merge_20260218_1858'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventparticipant',
            name='unique_display_name_per_event',
        ),
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.UniqueConstraint(models.F('user_event'), django.db.models.functions.text.Lower('display_name'), name='unique_display_name_per_event'),
        ),
    ]
