# Generated by Django 5.2 on 2026-03-28 20:17

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_eventparticipant_unique_display_name_per_event_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthedPasswordResetCode',
            fields=[
                ('user_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='authed_password_reset_code', serialize=False, to='api.useraccount')),
                ('reset_code', models.CharField(max_length=6)),
                ('created_at', api.models.DateTimeNoTZField(auto_now_add=True)),
            ],
        ),
    ]
