# Generated by Django 5.2 on 2026-05-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_authedpasswordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlogin',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='userlogin',
            name='user_agent_raw',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='usersession',
            name='user_agent_raw',
            field=models.TextField(null=True),
        ),
    ]
