# Generated by Django 5.2 on 2026-04-30 21:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_authedpasswordresetcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventparticipant",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
