# Generated by Django 5.2 on 2026-05-06 01:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_userlogin_ip_address_userlogin_user_agent_raw_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersession",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
