# Generated by Django 5.2 on 2026-04-30 21:04

import uuid
from django.db import migrations


def gen_uuid(apps, _):
    EventParticipant = apps.get_model("api", "EventParticipant")
    for participant in EventParticipant.objects.all():
        participant.public_id = uuid.uuid4()
        participant.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_eventparticipant_public_id"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
