# Generated by Django 5.2 on 2026-04-30 21:04

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_populate_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventparticipant",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
