# Generated by Django 5.2 on 2026-05-06 01:42

import uuid

from django.db import migrations


def gen_uuid(apps, _):
    UserSession = apps.get_model("api", "UserSession")
    for row in UserSession.objects.iterator():
        row.public_id = uuid.uuid4()
        row.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_usersession_public_id"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
