# Generated by Django 5.2 on 2026-05-06 01:42

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_populate_uuid_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersession",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
