# Generated by Django 5.2 on 2026-06-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_apply_unique_constraint'),
        ('api', '0031_apply_unique_constraint'),
    ]

    operations = [
    ]
