# Generated by Django 5.2 on 2026-06-19 18:53

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_merge_20260611_1318'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='urlcode',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('url_code'), name='unique_case_insensitive_url_code'),
        ),
    ]
