# Generated by Django 5.2 on 2026-08-20 01:14

import django.db.models.deletion
from django.db import migrations, models

import api.models


def delete_unverified_user_accounts(apps, _):
    """
    Deletes all unverified user accounts.
    """
    UnverifiedUserAccount = apps.get_model("api", "UnverifiedUserAccount")
    UnverifiedUserAccount.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_urlcode_unique_case_insensitive_url_code"),
    ]

    operations = [
        migrations.RunPython(
            delete_unverified_user_accounts,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="PasswordResetCode",
            fields=[
                (
                    "user_account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="password_reset_code",
                        serialize=False,
                        to="api.useraccount",
                    ),
                ),
                ("reset_code", models.CharField(max_length=6)),
                ("created_at", api.models.DateTimeNoTZField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="passwordresettoken",
            name="user_account",
        ),
        migrations.AlterField(
            model_name="unverifieduseraccount",
            name="verification_code",
            field=models.CharField(max_length=6, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name="AuthedPasswordResetCode",
        ),
        migrations.DeleteModel(
            name="PasswordResetToken",
        ),
    ]
