# Generated by Django 5.2 on 2026-07-09 17:46

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_urlcode_unique_case_insensitive_url_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="userevent",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True),
        ),
    ]
