# Generated by Django 5.2 on 2026-07-17 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_urlcode_unique_case_insensitive_url_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userevent',
            name='date_type',
            field=models.CharField(choices=[('GENERIC', 'Generic'), ('SPECIFIC', 'Specific'), ('CALENDAR', 'Calendar')], max_length=20),
        ),
        migrations.CreateModel(
            name='EventCalendarTimeslot',
            fields=[
                ('event_calendar_timeslot_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('user_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_timeslots', to='api.userevent')),
            ],
        ),
        migrations.CreateModel(
            name='EventCalendarAvailability',
            fields=[
                ('event_calendar_availability_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available')], max_length=20)),
                ('event_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_calendar_availabilities', to='api.eventparticipant')),
                ('event_calendar_timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_availabilities', to='api.eventcalendartimeslot')),
            ],
        ),
        migrations.AddIndex(
            model_name='eventcalendartimeslot',
            index=models.Index(fields=['user_event', 'date'], name='api_eventca_user_ev_f064a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventcalendartimeslot',
            constraint=models.UniqueConstraint(fields=('user_event', 'date'), name='unique_calendar_timeslot_per_event'),
        ),
        migrations.AddIndex(
            model_name='eventcalendaravailability',
            index=models.Index(fields=['event_participant'], name='api_eventca_event_p_f21bab_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventcalendaravailability',
            constraint=models.UniqueConstraint(fields=('event_participant', 'event_calendar_timeslot'), name='unique_participant_calendar_timeslot'),
        ),
    ]
