# Generated by Django 5.2 on 2026-08-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_passwordresetcode_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unverifieduseraccount",
            name="verification_code",
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name="unverifieduseraccount",
            name="email",
            field=models.EmailField(
                max_length=254, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
