# Generated by Django 5.2 on 2026-07-09 17:47

import uuid

from django.db import migrations


def gen_uuid(apps, _):
    UserEvent = apps.get_model("api", "UserEvent")
    for row in UserEvent.objects.iterator():
        row.public_id = uuid.uuid4()
        row.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_userevent_public_id"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
