# Generated by Django 5.2 on 2026-07-09 17:47

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_populate_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userevent",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
