# Generated by Django 5.2 on 2026-08-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_unverifieduseraccount_email_and_more'),
        ('api', '0036_apply_unique_constraint'),
    ]

    operations = [
    ]
