# Generated by Django 5.2 on 2026-08-31 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_userevent_date_type_eventcalendartimeslot_and_more'),
        ('api', '0036_apply_unique_constraint'),
    ]

    operations = [
    ]
