services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

  backend:
    image: ghcr.io/plan-cake/plancake-backend:${IMAGE_TAG:-latest}
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: ["sh", "./start.sh"]
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - LIVE_UPDATES_URL=redis://redis:6379/1
    depends_on:
      - redis

  frontend:
    image: ghcr.io/plan-cake/plancake-frontend:${IMAGE_TAG:-latest}
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    command: ["sh", "./start.sh"]
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
      - next_cache:/app/.next
    env_file:
      - ./frontend/.env
    environment:
      # The API URL for both the client and the Next.js server to communicate with the backend
      - INTERNAL_API_URL=http://backend:8000
      # For Next.js to detect file changes in Docker
      - WATCHPACK_POLLING=true
    depends_on:
      - backend

volumes:
  redis_data:
  node_modules:
  next_cache:
